# <span style="color:#4d79ff">Getting started with ndarray</span>
**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

## <span style="color:#4d79ff">How to create Rank 1 numpy arrays:</span>

In [1]:
import numpy as np                 # importing numpy library
an_array = np.array([3, 33, 333])  # creating a rank 1 array
print(type(an_array))              # get the type of ndarray:<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [2]:
# test the shape of this array
print(an_array.shape)  # one dimension and three elements

(3,)


In [3]:
# print each element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
# narrays are mutable]
an_array[0] = 888
print(an_array)

[888  33 333]


## <span style="color:#4d79ff">How to create a Rank 2 numpy array:</span>
A rank 2 **ndarray** is one with two dimensions. Notice the format below of [[row], [row]]. 2 dimensional arrays are great for representing matrices which are often useful in data science.

In [5]:
another = np.array([[11, 12, 13],[21, 22, 23]])  # create a rank 2 array
print(another)
print("The shape is 2 rows, 3 columns: ", another.shape) # rows x columns
print("Accessing elements [0,0], [0,1] and [1,0] of the ndarray: ",
      another[0,0],",",another[0,1],",",another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1] and [1,0] of the ndarray:  11 , 12 , 21


## <span style="color:#4d79ff">There are many ways to create numpy arrays:</span>
Here we create a number of different size arrays with different shapes and different pre-filled values. Numpy has a number of built in methods which
help us quickly and easily create multidimensional arrays.

In [6]:
# create a 2x2 array of zeros
ext1 = np.zeros((2,2))
ext1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [7]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex2 = np.eye(2,2)
ex2

array([[ 1.,  0.],
       [ 0.,  1.]])

In [8]:
# create a 2x2 array filled with 9.0
ex3 = np.full((2,2),9.0)
ex3

array([[ 9.,  9.],
       [ 9.,  9.]])

In [9]:
# create an array of ones
ex4 = np.ones((1,2))
ex4

array([[ 1.,  1.]])

In [10]:
# notice that the above ndarray is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [11]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
ex5

array([[ 0.2647979 ,  0.25977268],
       [ 0.00603639,  0.33830976]])

---

# <span style="color:#4d79ff">Array Indexing</span>

## <span style="color:#4d79ff">Slicing Indexing:</span>
Similar to the use of slice indexing with lists and strings. We can use slice indexing to pull out subregions of ndarrays.

In [18]:
# rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns

In [15]:
a_slice = an_array[:2,1:3]
print(a_slice)

array([[12, 13],
       [22, 23]])

<img style="float: left;" src='Files/array_slicing_example.png' width = 400><br><br><br><br><br><br><br><br>
When you modify a slice, you actually modify the underlying array
<img style="float: left;" src='Files/array_slicing_example2.png' width = 300>

In [20]:
print("Before:",an_array[0,1])
a_slice[0,0] = 1000
print("After:",an_array[0,1])

Before: 12
After: 12


In [19]:
# getting a copy of sliced an_array, without the pointers
a_slice = np.array(an_array[:2,1:3])

## <span style="color:#4d79ff">Use both integer indexing and slice indexing:</span>
We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [23]:
# create a rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [24]:
# using both integer indexing and slicing generates an array of lower rank
row_rank1 = an_array[1,:]    # rank 1 view
print(row_rank1,row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [25]:
# slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2,:]  # rank 2 view
print(row_rank2,row_rank2.shape)  # notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [26]:
# we can do the same thing for columns of an array:
print()
col_rank1 = an_array[:,1]
col_rank2 = an_array[:,1:2]

print(col_rank1,col_rank1.shape) # rank 1
print("-"*10)
print(col_rank2,col_rank2.shape) # rank 2


[12 22 32] (3,)
----------
[[12]
 [22]
 [32]] (3, 1)


## <span style="color:#4d79ff">Array Indexing for Changing Elements:</span>
Sometimes it's useful to use an array of indexes to access or change elements.

In [27]:
# create a new array
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34],
                     [41,42,43,44]])
print("Original Array:")
print(an_array)

Original Array:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [29]:
# create an array of indices
col_indices = np.array([0,1,2,0])
print("\nCol indices picked: ",col_indices)

row_indices = np.arange(4)
print("\nRows indices picked: ",row_indices)


Col indices picked:  [0 1 2 0]

Rows indices picked:  [0 1 2 3]


In [30]:
# examine the pairings of row_indices and col_indices.
for row,col in zip(row_indices,col_indices):
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [32]:
# select one element from each row
print("Values in the array at those indices: ",an_array[row_indices,col_indices])

Values in the array at those indices:  [11 22 33 41]


In [33]:
# change one element from each row using the indices selected
an_array[row_indices,col_indices] += 100000

print("\nChanged Array:")
print(an_array)


Changed Array:
[[100011     12     13     14]
 [    21 100022     23     24]
 [    31     32 100033     34]
 [100041     42     43     44]]
