# <span style="color:#4d79ff">Getting started with ndarray</span>
**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

## <span style="color:#4d79ff">How to create Rank 1 numpy arrays:</span>

In [1]:
import numpy as np                 # importing numpy library
an_array = np.array([3, 33, 333])  # creating a rank 1 array
print(type(an_array))              # get the type of ndarray:<class 'numpy.ndarray'>

<class 'numpy.ndarray'>


In [2]:
# test the shape of this array
print(an_array.shape)  # one dimension and three elements

(3,)


In [3]:
# print each element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
# narrays are mutable]
an_array[0] = 888
print(an_array)

[888  33 333]


## <span style="color:#4d79ff">How to create a Rank 2 numpy array:</span>
A rank 2 **ndarray** is one with two dimensions. Notice the format below of [[row], [row]]. 2 dimensional arrays are great for representing matrices which are often useful in data science.

In [5]:
another = np.array([[11, 12, 13],[21, 22, 23]])  # create a rank 2 array
print(another)
print("The shape is 2 rows, 3 columns: ", another.shape) # rows x columns
print("Accessing elements [0,0], [0,1] and [1,0] of the ndarray: ",
      another[0,0],",",another[0,1],",",another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1] and [1,0] of the ndarray:  11 , 12 , 21


## <span style="color:#4d79ff">There are many ways to create numpy arrays:</span>
Here we create a number of different size arrays with different shapes and different pre-filled values. Numpy has a number of built in methods which
help us quickly and easily create multidimensional arrays.

In [6]:
# create a 2x2 array of zeros
ext1 = np.zeros((2,2))
ext1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [7]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex2 = np.eye(2,2)
ex2

array([[ 1.,  0.],
       [ 0.,  1.]])

In [8]:
# create a 2x2 array filled with 9.0
ex3 = np.full((2,2),9.0)
ex3

array([[ 9.,  9.],
       [ 9.,  9.]])

In [9]:
# create an array of ones
ex4 = np.ones((1,2))
ex4

array([[ 1.,  1.]])

In [10]:
# notice that the above ndarray is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [11]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
ex5

array([[ 0.2647979 ,  0.25977268],
       [ 0.00603639,  0.33830976]])