# <span style="color:#4d79ff">Getting started with ndarray</span>
**ndarrays** are time and space-efficient multidimensional arrays at the core of numpy. Like the data structures in Week 2, let's get started by creating ndarrays using the numpy package.

## <span style="color:#4d79ff">How to create Rank 1 numpy arrays:</span>

In [1]:
import numpy as np                 # importing numpy library

In [2]:
an_array = np.array([3, 33, 333])  # creating a rank 1 array
print(type(an_array))              # get the type of ndarray:<class 'numpy.ndarray'>
# test the shape of this array
print(an_array.shape)  # one dimension and three elements

<class 'numpy.ndarray'>
(3,)


In [3]:
# print each element
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [4]:
# narrays are mutable]
an_array[0] = 888
print(an_array)

[888  33 333]


## <span style="color:#4d79ff">How to create a Rank 2 numpy array:</span>
A rank 2 **ndarray** is one with two dimensions. Notice the format below of [[row], [row]]. 2 dimensional arrays are great for representing matrices which are often useful in data science.

In [5]:
another = np.array([[11, 12, 13],[21, 22, 23]])  # create a rank 2 array
print(another)
print("The shape is 2 rows, 3 columns: ", another.shape) # rows x columns
print("Accessing elements [0,0], [0,1] and [1,0] of the ndarray: ",
      another[0,0],",",another[0,1],",",another[1,0])

[[11 12 13]
 [21 22 23]]
The shape is 2 rows, 3 columns:  (2, 3)
Accessing elements [0,0], [0,1] and [1,0] of the ndarray:  11 , 12 , 21


## <span style="color:#4d79ff">There are many ways to create numpy arrays:</span>
Here we create a number of different size arrays with different shapes and different pre-filled values. Numpy has a number of built in methods which
help us quickly and easily create multidimensional arrays.

In [6]:
# create a 2x2 array of zeros
ext1 = np.zeros((2,2))
ext1

array([[ 0.,  0.],
       [ 0.,  0.]])

In [7]:
# create a 2x2 matrix with the diagonal 1s and the others 0
ex2 = np.eye(2,2)
ex2

array([[ 1.,  0.],
       [ 0.,  1.]])

In [8]:
# create a 2x2 array filled with 9.0
ex3 = np.full((2,2),9.0)
ex3

array([[ 9.,  9.],
       [ 9.,  9.]])

In [9]:
# create an array of ones
ex4 = np.ones((1,2))
ex4

array([[ 1.,  1.]])

In [10]:
# notice that the above ndarray is actually rank 2, it is a 2x1 array
print(ex4.shape)

# which means we need to use two indexes to access an element
print()
print(ex4[0,1])

(1, 2)

1.0


In [11]:
# create an array of random floats between 0 and 1
ex5 = np.random.random((2,2))
ex5

array([[ 0.9286956 ,  0.64293478],
       [ 0.9822282 ,  0.56377135]])

---

# <span style="color:#4d79ff">Array Indexing</span>

## <span style="color:#4d79ff">Slicing Indexing:</span>
Similar to the use of slice indexing with lists and strings. We can use slice indexing to pull out subregions of ndarrays.

In [12]:
# rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 columns

In [13]:
a_slice = an_array[:2,1:3]
print(a_slice)

[[12 13]
 [22 23]]


<img style="float: left;" src='Files/array_slicing_example.png' width = 400><br><br><br><br><br><br><br><br>
When you modify a slice, you actually modify the underlying array
<img style="float: left;" src='Files/array_slicing_example2.png' width = 300>

In [14]:
print("Before:",an_array[0,1])
a_slice[0,0] = 1000
print("After:",an_array[0,1])

Before: 12
After: 1000


In [15]:
# getting a copy of sliced an_array, without the pointers
a_slice = np.array(an_array[:2,1:3])

## <span style="color:#4d79ff">Use both integer indexing and slice indexing:</span>
We can use combinations of integer indexing and slice indexing to create different shaped matrices.

In [16]:
# create a rank 2 array of shape (3,4)
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [17]:
# using both integer indexing and slicing generates an array of lower rank
row_rank1 = an_array[1,:]    # rank 1 view
print(row_rank1,row_rank1.shape)  # notice only a single []

[21 22 23 24] (4,)


In [18]:
# slicing alone: generates an array of the same rank as the an_array
row_rank2 = an_array[1:2,:]  # rank 2 view
print(row_rank2,row_rank2.shape)  # notice the [[ ]]

[[21 22 23 24]] (1, 4)


In [19]:
# we can do the same thing for columns of an array:
print()
col_rank1 = an_array[:,1]
col_rank2 = an_array[:,1:2]

print(col_rank1,col_rank1.shape) # rank 1
print("-"*10)
print(col_rank2,col_rank2.shape) # rank 2


[12 22 32] (3,)
----------
[[12]
 [22]
 [32]] (3, 1)


## <span style="color:#4d79ff">Array Indexing for Changing Elements:</span>
Sometimes it's useful to use an array of indexes to access or change elements.

In [20]:
# create a new array
an_array = np.array([[11,12,13,14],
                     [21,22,23,24],
                     [31,32,33,34],
                     [41,42,43,44]])
print("Original Array:")
print(an_array)

Original Array:
[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]
 [41 42 43 44]]


In [21]:
# create an array of indices
col_indices = np.array([0,1,2,0])
print("\nCol indices picked: ",col_indices)

row_indices = np.arange(4)
print("\nRows indices picked: ",row_indices)


Col indices picked:  [0 1 2 0]

Rows indices picked:  [0 1 2 3]


In [22]:
# examine the pairings of row_indices and col_indices.
for row,col in zip(row_indices,col_indices):
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [23]:
# select one element from each row
print("Values in the array at those indices: ",an_array[row_indices,col_indices])

Values in the array at those indices:  [11 22 33 41]


In [24]:
# change one element from each row using the indices selected
an_array[row_indices,col_indices] += 100000

print("\nChanged Array:")
print(an_array)


Changed Array:
[[100011     12     13     14]
 [    21 100022     23     24]
 [    31     32 100033     34]
 [100041     42     43     44]]


# <span style="color:#4d79ff">Boolean Indexing</span>

## <span style="color:#4d79ff">Array Indexing for changing elements:</span>

In [25]:
# create a 3x2 array
an_array = np.array([[11,12],[21,22],[31,32]])
print(an_array)

[[11 12]
 [21 22]
 [31 32]]


In [26]:
# create a filter which will be boolean values for each element
filter = an_array > 15
filter

array([[False, False],
       [ True,  True],
       [ True,  True]], dtype=bool)

Notice that the filter is a same size ndarray as an_array which is filled
with True for each element whose corresponding element in an_array which is
greater than 15 and False for those elements whose value is less than 15

In [27]:
# filter by criteria
print(an_array[filter])

[21 22 31 32]


In [31]:
# we can do complex filters in a single step
an_array[an_array % 2 == 0]

array([12, 22, 32])

What is particularly useful is that we can actually change elements in the
array applying a similar logical filter. Let's add 100 to all the even values.

In [32]:
an_array[an_array % 2 == 0] += 100
print(an_array)

[[ 11 112]
 [ 21 122]
 [ 31 132]]


# <span style="color:#4d79ff">Datatypes and Array Operations</span>

## <span style="color:#4d79ff">Datatypes:</span>

In [33]:
ex1 = np.array([11,12]) # python assigns the data type
print(ex1.dtype)

int32


In [34]:
ex2 = np.array([11.0,12.0]) # python assigns the data type
print(ex2.dtype)

float64


In [35]:
ex3 = np.array([11,12],dtype=np.int64) # you set explicitly the data type
print(ex3.dtype)

int64


In [45]:
ex4 = np.array([11.1,12.7],dtype=np.int64) # force floats into integers (truncate)
print(ex4.dtype)
print("-"*2,"Converted","-"*2)
print(ex4)

int64
-- Converted --
[11 12]


In [46]:
# force integers into floats
ex5 = np.array([11,21],dtype=np.float64)
print(ex5.dtype)
print("-"*2,"Converted","-"*2)
print(ex5)

float64
-- Converted --
[ 11.  21.]


## <span style="color:#4d79ff">Arithmetic Array Operations:</span>

In [47]:
x = np.array([[111,112],[121,122]],dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]],dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[ 211.1  212.1]
 [ 221.1  222.1]]


**For many of these operations work, there needs to be an aligning of dimensions.**

In [49]:
# add
print(x + y)        # the plus sign works -- BETTER FOR CODE READABILITY
print()
print(np.add(x,y))  #so does the numpy function "add"

[[ 322.1  324.1]
 [ 342.1  344.1]]

[[ 322.1  324.1]
 [ 342.1  344.1]]


In [50]:
# substract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [51]:
# multiply
print(x*y)
print()
print(np.multiply(x,y))

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]

[[ 23432.1  23755.2]
 [ 26753.1  27096.2]]


In [52]:
# divide
print(x/y)
print(np.divide(x,y))

[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]
[[ 0.52581715  0.52805281]
 [ 0.54726368  0.54930212]]


In [53]:
# square root
print(np.sqrt(x))

[[ 10.53565375  10.58300524]
 [ 11.          11.04536102]]


In [54]:
# exponent (e**x)
print(np.exp(x))

[[  1.60948707e+48   4.37503945e+48]
 [  3.54513118e+52   9.63666567e+52]]
